package gui.environment;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.JOptionPane;

import file.BasicFileReader;
import file.BasicFileWriter;

/**
 *
 * @author arineiza
 */
public class ConfigurationEnvironment extends javax.swing.JFrame {

    /** Creates new form Configuration */
    public ConfigurationEnvironment(EnvironmentFrame frame) {
    	
    	/** LOGGER - Begin */
		SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");  
		frame.getEnvironment().getLogArea().append("\n" + sdf.format(new Date()) + " - Configuration - START");
		/** LOGGER - End */	
		
        initComponents();
        this.setAlwaysOnTop(true);
        this.frame = frame;
        this.frame.setEnabled(false);

        File fLocalDir = new File("").getAbsoluteFile();
		String strLocalDir = fLocalDir.getPath();
    	
		BasicFileReader configFile = new BasicFileReader(strLocalDir+"//config.txt");
						
		if(configFile.open()){
			String separator = configFile.readLine();
			if(separator.equalsIgnoreCase("DEFAULT"))
				jRadioButton1.setSelected(true);
			else if(separator.equalsIgnoreCase("SPACE"))
				jRadioButton2.setSelected(true);
			else if(separator.equalsIgnoreCase("NOTHING") || separator.equalsIgnoreCase(""))
				jRadioButton4.setSelected(true);
			else{ 
				jRadioButton3.setSelected(true);
				jTextField1.setEditable(true);
			}
			configFile.close();
		}
		else{
			jRadioButton1.setSelected(true);
		}
        
		this.setLocation( this.frame.getX()+ (int) this.frame.getSize().getWidth()/3,  this.frame.getY()+ (int) this.frame.getSize().getHeight()/3);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    private void initComponents() {


        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField1.setEnabled(false);
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jRadioButton4 = new javax.swing.JRadioButton();

        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        buttonGroup1.add(jRadioButton3);
        buttonGroup1.add(jRadioButton4);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);


        jRadioButton1.setText("Default (\",\")");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });

        jRadioButton2.setText("Space (\" \")");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });

        jRadioButton3.setText("Other");
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton3MouseClicked(evt);
            }
        });
       

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Input Separator");

        jRadioButton4.setText("Nothing");
        jRadioButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton4)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(jLabel1))))
                        .addGap(39, 39, 39))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pack();
    }

    //Cancel button
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
        this.frame.setEnabled(true);
    }
    
    //Ok button
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
    	
    	File fLocalDir = new File("").getAbsoluteFile();
		String strLocalDir = fLocalDir.getPath();
		SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");  
		BasicFileWriter configFile = new BasicFileWriter(strLocalDir+"//config.txt");
						
		if(configFile.open()){
			if(jRadioButton1.isSelected()){
				configFile.writeLine("DEFAULT");
				frame.getEnvironment().getLogArea().append("\n" + sdf.format(new Date()) + " - Configuration - DEFAULT");
			}
			if(jRadioButton2.isSelected()){
				configFile.writeLine("SPACE");
				frame.getEnvironment().getLogArea().append("\n" + sdf.format(new Date()) + " - Configuration - SPACE");
			}
			if(jRadioButton3.isSelected()){
				if(!jTextField1.getText().equals("")){
					configFile.writeLine(jTextField1.getText());
					frame.getEnvironment().getLogArea().append("\n" + sdf.format(new Date()) + " - Configuration - " + jTextField1.getText());
				}
				else{
					JOptionPane.showMessageDialog(null, 
		                    "NOTHING was applied:" +
		                    " No character was typed.",
		                    "Configuration", JOptionPane.INFORMATION_MESSAGE);
					frame.getEnvironment().getLogArea().append("\n" + sdf.format(new Date()) + " - Configuration - NOTHING");
				}	
			}
			
			if(jRadioButton4.isSelected()){
				configFile.writeLine("NOTHING");
				frame.getEnvironment().getLogArea().append("\n" + sdf.format(new Date()) + " - Configuration - NOTHING");
			}
			configFile.close();
		}
		this.dispose();
        this.frame.setEnabled(true);
        
    	/** LOGGER - Begin */
		frame.getEnvironment().getLogArea().append("\n" + sdf.format(new Date()) + " - Configuration - END");
		/** LOGGER - End */	
		
    }


    
    private void jRadioButton3MouseClicked(java.awt.event.MouseEvent evt) {
            jTextField1.setEnabled(true);
    }

    private void jRadioButton4MouseClicked(java.awt.event.MouseEvent evt) {
        jTextField1.setEnabled(false);
    }

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {
         jTextField1.setEnabled(false);
    }

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {
        jTextField1.setEnabled(false);
    }


    // Variables declaration 
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    
    private EnvironmentFrame frame;

  
}